<template>
  <div class="about">
    <b-container class="container">
      <b-row>
        <b-col>
          <img alt="City Clear logo" src="../assets/logo-about.png"> <br>
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
           blabla
           blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          blabla
          </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
  export default {
  }
</script>
>

<style scoped lang="scss">
  .about{
    background: white;
    opacity: 0.8;
  }

  img {
    width: 15%;
    height: auto;
  }

  @media (max-width: 800px) {
    img {
      width: 30%;
      height: auto;
    }
   }

  @media (max-width: 600px) {
    img {
      width: 30%;
      height: auto;
    }
  }
</style>